# Local Template for setting configurations for local development
server:
  port: 8000

spring:
  datasource:
    username: root
    password: 100698Sb!
    url: jdbc:mysql://localhost:3307

security:
  allowed:
    domains: "*"
