name: Sql Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://marcs-microservice.herokuapp.com/authenticate'
        method: 'POST'
        username: sambutler1017@icloud.com
        password: 78e05bf74fad284798a195ec2ff3ae6D!
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}
