name: Sql Script

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  cypress_testing:
    runs-on: ubuntu-latest
    
    services:
      mysql:
          image: mysql:5.7
          env:
              MYSQL_DATABASE: hydro_db
              MYSQL_USER: sambutler1017
              MYSQL_PASSWORD: password
              MYSQL_ROOT_PASSWORD: 100698Sb!
          ports:
              - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - name: Create DB structure
        run: |
          sudo /lib/systemd/systemd-sysv-install enable mysql
          sudo systemctl enable mysql.service
          sudo systemctl start mysql.service
          sudo systemctl status mysql.service
